### 강의 목록 조회
GET http://localhost:8888/api/courses

### 강의 등록
POST http://localhost:8888/api/courses
Content-Type: application/json

{
  "title": "자바의 정석",
  "tutor": "남궁성"
}

### 강의 수정
PUT http://localhost:8888/api/courses/1
Content-Type: application/json

{
  "title": "프론트엔드의 꽃, React",
  "tutor": "임민영"
}

### 강의 삭제
DELETE http://localhost:8888/api/courses/1